TodoApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TodoApp.Core;

namespace TodoApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TodoApp/Controllers/ProjectsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TodoApp.Core;
using TodoApp.Core.Entity;

namespace TodoApp.Controllers
{
    public class ProjectsController : Controller
    {
        private readonly AppDbContext _context;

        public ProjectsController(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var appDbContext = _context.Projects.ToListAsync();
            return View(await appDbContext);
        }
        public async Task<IActionResult> GetProject(int? id)
        {
            if (id == null || _context.Projects == null)
            {
                return NotFound();
            }

            var task = await _context.Tasks.Include(p => p.Project).FirstOrDefaultAsync(m => m.Id == id);
            if (task == null)
            {
                return NotFound();
            }

            return View(task);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create([Bind("Id,Name")] Project project)
        {
            if(ModelState.IsValid)
            {
                _context.AddAsync(project);
                _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(project);
        }

    }
}

TodoApp/Controllers/TasksController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TodoApp.Core.Interfaces;

namespace TodoApp.Controllers
{
    public class TasksController : Controller
    {
        private readonly AppDbContext _context;
        private readonly ITaskService _taskService;
        private readonly DateTime date = DateTime.Today;
        public string taskJsonFile = "Maded_Tasks.json";
        public string taskFile = "Maded_Tasks.csv";
        public bool b = false;
        public TasksController(AppDbContext context, ITaskService taskService)
        {
            _context = context;
            _taskService = taskService;
        }
       
        // GET: Tasks
        public async Task<IActionResult> Index(string searchString)
        {
            if (_context.Tasks == null)
            {
                return Problem("Entity set 'MvcMovieContext.Movie'  is null.");
            }

            var task = _taskService.Search(searchString);
            return View(task);    
        }
        public async Task<IActionResult> GetTasks(int id)
        {
            var appDbContext = _taskService.GetTasks(id);
            return View(appDbContext);
        }
        public async Task<IActionResult> GetTodayTasks()
        {
            var appDbContext = _taskService.GetTodayTasks();
            return View(appDbContext);
        }
        public async Task<IActionResult> GetUpcomingTasks()
        {
            var appDbContext = _context.Tasks.Include(t => t.Project).Where(p => p.Deadline.Date >= date);
            return View(await appDbContext.ToListAsync());
        }
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Tasks == null)
            {
                return NotFound();
            }

            var task = await _context.Tasks
                .Include(t => t.Project)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (task == null)
            {
                return NotFound();
            }

            return View(task);
        }
        public IActionResult Create()
        {
            ViewData["ProjectId"] = new SelectList(_context.Projects, "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Time,Deadline,IsDone,ProjectId")] Core.Entity.Task task)
        {
            _taskService.Add(task);
             return RedirectToAction(nameof(Index));
        }
        
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Tasks == null)
            {
                return NotFound();
            }

            var task = await _context.Tasks.FindAsync(id);
            if (task == null)
            {
                return NotFound();
            }
            ViewData["ProjectId"] = new SelectList(_context.Projects, "Id", "Name", task.Id);
            return View(task);
        }

        // POST: Tasks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Time,IsDone,ProjectId")] Core.Entity.Task task)
        {
            if (id != task.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _taskService.Update(task);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TaskExists(task.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProjectId"] = new SelectList(_context.Projects, "Id", "Name", task.Id);
            return View(task);
        }
        
        // GET: Tasks/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Tasks == null)
            {
                return NotFound();
            }
            var task = await _context.Tasks
                .FirstOrDefaultAsync(m => m.Id == id);

            if (task == null)
            {
                return NotFound();
            }
            
            if (task != null)
            {

                task.IsDone = true;
                task.serializeJson(task, taskJsonFile);
                task.deserializeJson(task, taskFile);
                _context.Tasks.Remove(task);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // POST: Tasks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Tasks == null)
            {
                return Problem("Entity set 'AppDbContext.Tasks'  is null.");
            }
            _taskService.Delete(id);
            return RedirectToAction(nameof(Index));
        }

        private bool TaskExists(int id)
        {
          return _context.Tasks.Any(e => e.Id == id);
        }
    }
}

TodoApp/ViewComponents/ProjectViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using TodoApp.Core.Entity;

namespace TodoApp.ViewComponents
{
    [ViewComponent(Name = "Project")]
    public class ProjectViewComponent : ViewComponent
    {
        private readonly AppDbContext _context;
        public ProjectViewComponent(AppDbContext applicationDbContext)
        {
            _context = applicationDbContext;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View("Index", _context.Projects.ToList());
        }
    }
}

TodoApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

<!-- Подключение библиотеки Toastr -->
<link href="https://cdn.jsdelivr.net/npm/toastr@2.1.4/toastr.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/toastr@2.1.4/toastr.min.js"></script>

<script>
toastr.info('Привет, это всплывающее уведомление!', 'Заголовок уведомления', {
    timeOut: 5000 // Время, через которое уведомление исчезнет (в миллисекундах)
});

</script>

TodoApp/Views/Projects/Create.cshtml
@model TodoApp.Core.Entity.Project

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Project</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <p></p>
            <div class="form-group">
                <input type="submit" value="Create" style="background: #D03B2E" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

TodoApp/Views/Projects/GetProject.cshtml
@model IEnumerable<TodoApp.Core.Entity.Project>

@{
    ViewData["Title"] = "GetProject";
}

<h1>GetProject</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

TodoApp/Views/Projects/Index.cshtml
@model IEnumerable<TodoApp.Core.Entity.Project>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a style="background: " asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>

            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

TodoApp/Views/Shared/Components/Project/Index.cshtml
@model IEnumerable<TodoApp.Core.Entity.Project>  
<ul>  
    @foreach(var item in Model)  
    {  
        <a class="middle-title-projects" asp-controller="Tasks" asp-action="GetTasks" asp-route-id="@item?.Id">@item.Name</a><p></p>
    }  
    <a class="create_project" asp-controller="Projects" asp-action="Create">
        Add project
    </a>
</ul>  

TodoApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head style="background:#202020">
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TodoApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TodoApp.styles.css" asp-append-version="true" />
    <script src="https://cdn.syncfusion.com/ej2/20.4.38/dist/ej2.min.js"></script>
    <link rel="stylesheet" href="https://cdn.syncfusion.com/ej2/20.4.38/material.css" />
</head>

<body style="background:#202020; color:#E1E1E1;">

    <nav class="navbar sticky-top">
            
            <div class="container-fluid py-2 px-4">
                <i class="fa-solid fa-magnifying-glass"></i>
                
                <div>
                    
                    <form asp-area="Tasks" asp-action="Index">
                        <p>
                            Find task by name: <input type="text" class="search-input" name="SearchString" />
                            <input type="submit" style="background: #D03B2E; color: #FEFFFF; border: 0; border-radius: 3px;" value="Filter" />
                        </p>
                    </form>
                TodoApp
                </div>
            </div>
        </nav>

    <div class="container">
        <partial name="_Sidebar" />      

        <main role="main" class="pb-3">

            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <ejs-scripts></ejs-scripts>
</body>
</div>

</html>

TodoApp/Views/Shared/_Sidebar.cshtml
<ejs-sidebar id="default-sidebar" width="15%" style="background:#242424; text-align: center;">
    <e-content-template>
        <div class="title-head">
            <div style="display:inline-block;"> Todoshechka </div>
        </div>
        
        <div class="types-of-task" style="padding-top:15%">
            <ul class="type-of-task-list">
                
                    <a asp-action="Index">Inbox</a><p></p>
                    
                    <a asp-controller="Tasks" asp-action="GetTodayTasks">Today</a><p></p>

                    <a asp-controller="Tasks" asp-action="GetUpcomingTasks">Upcoming</a><p></p>
               
            </ul>
        </div>
        <div class="main-middle-title-projects" style="padding-top:45%;">
            <a><h1>Projects</h1></a>
            <div class="middle-title-projcts" style="padding-top:15%";>
                 @await Component.InvokeAsync("Project")   
            </div>
        </div>
    </e-content-template>
</ejs-sidebar>

TodoApp/Views/Tasks/Create.cshtml
@model TodoApp.Core.Entity.Task

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Task</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TimeOfCreation" class="control-label"></label>
                <input asp-for="TimeOfCreation" class="form-control" />
                <span asp-validation-for="TimeOfCreation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Deadline" class="control-label"></label>
                <input asp-for="Deadline" class="form-control" />
                <span asp-validation-for="Deadline" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProjectId" class="control-label"></label>
                <select asp-for="ProjectId" class ="form-control" asp-items="ViewBag.ProjectId"></select>
            </div>
            <p></p>
            <div class="form-group">
                <input type="submit" style="background: #D03B2E" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

TodoApp/Views/Tasks/Delete.cshtml
@model TodoApp.Core.Entity.Task

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Task</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TimeOfCreation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TimeOfCreation)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsDone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsDone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Project)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Project.Name)
        </dd>
    </dl>
    
    <form asp-action="Index">

        <a asp-action="Index">Back to List</a>
    </form>
</div>

TodoApp/Views/Tasks/DeleteConfirmed.cshtml
@{
    ViewData["Title"] = "DeleteConfirmed";
}

<h1>DeleteConfirmed</h1>

TodoApp/Views/Tasks/Edit.cshtml
@model TodoApp.Core.Entity.Task

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Task</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TimeOfCreation" class="control-label"></label>
                <input asp-for="TimeOfCreation" class="form-control" />
                <span asp-validation-for="TimeOfCreation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IsDone" class="control-label"></label>
                <input asp-for="IsDone" class="form-control" />
                <span asp-validation-for="IsDone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProjectId" class="control-label"></label>
                <select asp-for="ProjectId" class="form-control" asp-items="ViewBag.ProjectId"></select>
                <span asp-validation-for="ProjectId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

TodoApp/Views/Tasks/GetTasks.cshtml
@model IEnumerable<TodoApp.Core.Entity.Task>

@{
    ViewData["Title"] = "GetTasks";
}

<h1>GetTasks</h1>

<p>
</p>
@foreach (var item in Model) {

    <div class="list-group">
  <a href="#"style="background: #202020;" class="list-group-item list-group-item-action flex-column align-items-start active">
    <div class="d-flex w-100 justify-content-between">
      <h5 class="mb-1">@Html.DisplayFor(modelItem => item.Name)</h5>
      <small>  @Html.DisplayFor(modelItem => item.Deadline)</small>
    </div>
    <p class="mb-1">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.</p>
    <small>@Html.DisplayFor(modelItem => item.Project.Name)</small>
    <h5 style="font-weight: bold;"> Is done?  @Html.CheckBoxFor(m => item.IsDone, new {  @class="MyCheckBox", @onclick="opennewwindow("+@item.Id+", false);" }) </h5>
    <script>  
    function activeClick(cb) {  
      @item.IsDone = cb.checked;  
     }  
</script>  
  </a>
</div>
}
    <a asp-action="Create" style="background: #D03B2E; color: #FEFFFF">Add new task</a>

<p>
<script type="text/javascript">
    function opennewwindow(id, bool) {
        var retVal = confirm("You can't cancel this action. Are you sure?");
            if (retVal == true) {
                window.location.href = '@Url.Action("Delete")?id=' + id
            } 
            else {
                document.location.reload(true)
            }
    }
</script>

TodoApp/Views/Tasks/GetTodayTasks.cshtml
@model IEnumerable<TodoApp.Core.Entity.Task>

@{
    ViewData["Title"] = "GetTodayTasks";
}

<h1>GetTodayTasks</h1>


@foreach (var item in Model) {

    <div class="list-group">
  <a href="#" class="list-group-item list-group-item-action flex-column align-items-start active">
    <div class="d-flex w-100 justify-content-between">
      <h5 class="mb-1">@Html.DisplayFor(modelItem => item.Name)</h5>
      <small>  @Html.DisplayFor(modelItem => item.Deadline)</small>
    </div>
    <p class="mb-1">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.</p>
    <small>@Html.DisplayFor(modelItem => item.Project.Name)</small>
    <h5 style="font-weight: bold;"> Is done?  @Html.CheckBoxFor(m => item.IsDone, new {  @class="MyCheckBox", @onclick="opennewwindow("+@item.Id+", false);" }) </h5>
  </a>
</div>
}

<script type="text/javascript">
    function opennewwindow(id, bool) {
        var retVal = confirm("You can't cancel this action. Are you sure?");
            if (retVal == true) {
                window.location.href = '@Url.Action("Delete")?id=' + id
            } 
            else {
                document.location.reload(true)
            }
    }
</script>

TodoApp/Views/Tasks/GetUpcomingTasks.cshtml
@model IEnumerable<TodoApp.Core.Entity.Task>

@{
    ViewData["Title"] = "GetUpcomingTasks";
}

<h1>GetUpcomingTasks</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
@foreach (var item in Model) {

    <div class="list-group">
  <a href="#" class="list-group-item list-group-item-action flex-column align-items-start active">
    <div class="d-flex w-100 justify-content-between">
      <h5 class="mb-1">@Html.DisplayFor(modelItem => item.Name)</h5>
      <small>  @Html.DisplayFor(modelItem => item.Deadline)</small>
    </div>
    <p class="mb-1">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.</p>
    <small>@Html.DisplayFor(modelItem => item.Project.Name)</small>
    <h5 style="font-weight: bold;"> Is done?  @Html.CheckBoxFor(m => item.IsDone, new {  @class="MyCheckBox", @onclick="opennewwindow("+@item.Id+", false);" }) </h5>
    <script>  
    function activeClick(cb) {  
      @item.IsDone = cb.checked;  
     }  
</script>  
  </a>
</div>
}

      <script type="text/javascript">
    function opennewwindow(id, bool) {
        var retVal = confirm("You can't cancel this action. Are you sure?");
            if (retVal == true) {
                window.location.href = '@Url.Action("Delete")?id=' + id
            } 
            else {
                document.location.reload(true)
            }
    }
</script>

TodoApp/Views/Tasks/Index.cshtml
@model IEnumerable<TodoApp.Core.Entity.Task>

@{
    ViewData["Title"] = "Index";
}
<p></p>
<h1>Tasks</h1>
<p></p>
@foreach (var item in Model) {


<div id="list-group">
  <a href="#" style="background: #202020; border-top:none; border-left:none; border-right:none; border-bottom: 1px solid @item.ChangeColor(); padding: 0 20px"; class="list-group-item list-group-item-action flex-column align-items-start active">
    <div class="d-flex w-100 justify-content-between" style="color:@item.ChangeColor()">
      <h5 class="mb-1" style="color:@item.ChangeColor()">@Html.DisplayFor(modelItem => item.Name)</h5>
      <small id="deadline-status">  @Html.DisplayFor(modelItem => item.Deadline)</small>
    </div>
    <p class="mb-1">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.</p>
    <small>
                @if (item.Project != null){
                    Html.DisplayFor(modelItem => item.Project.Name);
                }
                else
                {
                    Html.DisplayFor(modelItem => item.Name);
                }
    </small>
    <small><h5 style="font-weight: bold;"> Is done?  @Html.CheckBoxFor(m => item.IsDone, new {  @class="MyCheckBox", @onclick="opennewwindow("+@item.Id+", false);" }) </h5></small>
    <script>  
    function activeClick(cb) {  
      @item.IsDone = cb.checked;  
     }  
</script>  
  </a>
</div>
}
    <a asp-action="Create" >Add new task</a>
<p>
<script type="text/javascript">
    function opennewwindow(id, bool) {
        var retVal = confirm("You can't cancel this action. Are you sure?");
            if (retVal == true) {
                window.location.href = '@Url.Action("Delete")?id=' + id
            } 
            else {
                document.location.reload(true)
            }
    }
</script>